"""empty message

Revision ID: 573a026eaa03
Revises: 740a84501e39
Create Date: 2021-10-31 19:25:40.827324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573a026eaa03'
down_revision = '740a84501e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('modify_date', sa.DateTime(), nullable=True))
    op.add_column('list', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'modify_date')
    op.drop_column('comments', 'modify_date')
    # ### end Alembic commands ###
